org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,)
forge_version=47.4.23
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=crystal_gacha
mod_name=Crystal Gacha
mod_license=All Rights Reserved
mod_version=2.0
mod_group_id=com.cosmicbarri
mod_authors=cosmic-barri, Bonnielfid
mod_description=Adds the gacha from Ark
geckolib_version=4.8.3
